# Generated by Django 6.0 on 2026-01-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="overview",
            field=models.TextField(blank=True, null=True),
        ),
    ]
