# Generated by Django 6.0 on 2026-01-09 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="dark_theme",
            new_name="dark_mode",
        ),
    ]
