# Generated by Django 6.0 on 2026-01-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_rename_dark_theme_profile_dark_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="favorite_genre",
            field=models.CharField(blank=True, default="none set", max_length=50),
        ),
    ]
